version: "3"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: DAWGrupo3
            MYSQL_DATABASE: daw_quotes
            MYSQL_USER: daw
            MYSQL_PASSWORD: DAWGrupo3
    app:
        image: sigma98/app:3.0.1
        restart: on-failure
        links:
            - db
        depends_on:
            - db
        ports:
            - "8080:8443"
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db/daw_quotes?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            SPRING_DATASOURCE_USERNAME: daw
            SPRING_DATASOURCE_PASSWORD: DAWGrupo3